### ISSUE TITLE
error de version en red

### ISSUE THREAD

**Issue by rodrygombia** [Dte-ba/pad#15]
Cuando se levanta como servidor en una maquina de PAD BA el portable y se quiere ingresar desde otra maquina externa esa externa levanta el PAD 5 la version con la nubecita y las 10 secciones

**Comment by delmosaurio** [comment]
La versión anterior del PAD (5) corre como servicio at background, debe de seguir corriendo la versión vieja del pad.

Win:  Corroborar que el no este el archivo Inicio>Inicio>pad
GNU: Corroborar que no este corriendo el archivo /etc/init.d/pad

El bug no es de la aplicación PAD si no del ambiente donde se esta corriendo.

**Comment by delmosaurio** [comment]
Para Huayra pude probarse matar el servicio

```
$: sudo service pad stop 
```

Para Windows, antes de correr la aplicación Nw.js ver si no esta corriendo un servicio del tipo `node.exe`

**Comment by rodrygombia** [comment]
okey ahi me fijoo
