### ISSUE TITLE
contenido tarda en huayra

### ISSUE THREAD

**Issue by rodrygombia** [Dte-ba/pad#19]
Al querer ingresar a un portable por la red que fue levantado en huayra tarda horrores en cargar los paquetes.
Esto en windows no pasa, si levantas el servidor en windows las otras maquinas lo levantan al toque

**Comment by delmosaurio** [comment]
Este Issue debería considerarse igual al #20 lo cierro, si cuando se arregla en 20 sigue con problemas, lo reabrimos.
