### ISSUE TITLE
Descargar escritorio PAD desde la web

### ISSUE THREAD

**Issue by Claucode** [Dte-ba/pad#31]
Hola! Estoy teniendo inconvenientes para ver y bajar el PAD desde el sitio web. Al presionar el **botón PAD Online** se direcciona a http://pad.nticx.net/ y aparece un mensaje que indica: This domain name expired.
Al querer descargarlo desde el sitio []((http://padbuenosaires.abc.gov.ar/descarga.html) ) da un error (404 File not found), tanto en la opción de Windows 32 como en GNULinux 32 y GNULinux 64. El enlace GNU/Linux 64 figura repetido.

**Comment by rodrygombia** [comment]
Hola Clau ese dominio ya estamos dejando de usarlo, y en breve se borrará, si es que ya no lo hizo.
La dirección actual es 
http://dte.abc.gov.ar/padweb
Recién me fije y esta funcionando bien.

**Comment by Claucode** [comment]
Genial !! Abrí la web del PAD y ya se puede descargar y ver online. 
Gracias! Saludos
