### ISSUE TITLE
Pad Portable para Huayra 2.x

### ISSUE THREAD

**Issue by apalestrini** [Dte-ba/pad#5]
Hacer correr la versión Portable con nw.js, para las versiones de Huayra, en un principio la para las 2.X. Hasta se probó siguiendo los mismos pasos de uso en Winx y reportó la imagen que se adjunta.
![reporte huyra](https://cloud.githubusercontent.com/assets/6919636/14499132/61c71326-0173-11e6-9da5-2fbcaac3644b.PNG)

**Comment by delmosaurio** [comment]
El problema se da cuando se ejecuta con una versión de nwjs que no contiene DevTools, corregido en tag v6.1.4.
